# Generated by Django 2.1.4 on 2019-01-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreeLiveShow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tel',
            field=models.CharField(default=123456, max_length=15, verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
