# Generated by Django 2.1.4 on 2019-01-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThreeLiveShow', '0002_patient_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='mailAdress',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
