# Generated by Django 2.1.4 on 2019-01-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThreeLiveShow', '0003_auto_20190101_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
    ]
